export const UPDATE_EXCHANGE_RATE_FOR_EUR = "UPDATE_EXCHANGE_RATE_FOR_EUR";
export const UPDATE_EXCHANGE_RATE_FOR_USD = "UPDATE_EXCHANGE_RATE_FOR_USD";
export const UPDATE_EXCHANGE_RATE_FOR_GBP = "UPDATE_EXCHANGE_RATE_FOR_GBP";

export const ADD_TO_EUR_WALLET = "ADD_TO_EUR_WALLET";
export const ADD_TO_USD_WALLET = "ADD_TO_USD_WALLET";
export const ADD_TO_GBP_WALLET = "ADD_TO_GBP_WALLET";